# Generated by Django 4.2.5 on 2023-11-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('CampusID', models.AutoField(primary_key=True, serialize=False)),
                ('CampusName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('FacilityID', models.AutoField(primary_key=True, serialize=False)),
                ('FacilityName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('HostelID', models.AutoField(primary_key=True, serialize=False)),
                ('HostelName', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=1000)),
                ('ContactNumber', models.CharField(max_length=11)),
                ('Website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('RoomNumber', models.CharField(max_length=10)),
                ('RoomType', models.CharField(max_length=50)),
                ('Availability', models.BooleanField(default=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('HostelID', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Comment', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('HostelFacilityID', models.AutoField(primary_key=True, serialize=False)),
                ('FacilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facility')),
                ('HostelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('RoomID', models.IntegerField()),
                ('CheckInDate', models.DateField()),
                ('CheckOutDate', models.DateField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
