# Generated by Django 5.0 on 2023-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='HostelImage',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
    ]
