# Generated by Django 5.0 on 2023-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hostel_description_room_hostelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='RoomImage',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
