# Generated by Django 5.0 on 2023-12-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelUser',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hosteluser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hosteluser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
