# Generated by Django 5.0 on 2023-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hosteluser_alter_booking_userid_alter_review_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteluser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
