# Generated by Django 5.0 on 2023-12-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_checkindate_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='UserID',
            new_name='HostelUserID',
        ),
    ]
