# Generated by Django 5.0 on 2023-12-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_userid_booking_hosteluserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room'),
        ),
    ]
